package com.poc.domain;
// default package
// Generated Jun 7, 2016 5:01:25 PM by Hibernate Tools 4.3.1.Final

/**
 * AudtbChangedetails generated by hbm2java
 */
public class AudtbChangedetails implements java.io.Serializable {

	private AudtbChangedetailsId id;

	public AudtbChangedetails() {
	}

	public AudtbChangedetails(AudtbChangedetailsId id) {
		this.id = id;
	}

	public AudtbChangedetailsId getId() {
		return this.id;
	}

	public void setId(AudtbChangedetailsId id) {
		this.id = id;
	}

}
