package com.poc.domain;
// default package
// Generated Jun 7, 2016 5:01:25 PM by Hibernate Tools 4.3.1.Final

/**
 * AudtbBodmapId generated by hbm2java
 */
public class AudtbBodmapId implements java.io.Serializable {

	private String aubodname;
	private String autablename;

	public AudtbBodmapId() {
	}

	public AudtbBodmapId(String aubodname, String autablename) {
		this.aubodname = aubodname;
		this.autablename = autablename;
	}

	public String getAubodname() {
		return this.aubodname;
	}

	public void setAubodname(String aubodname) {
		this.aubodname = aubodname;
	}

	public String getAutablename() {
		return this.autablename;
	}

	public void setAutablename(String autablename) {
		this.autablename = autablename;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AudtbBodmapId))
			return false;
		AudtbBodmapId castOther = (AudtbBodmapId) other;

		return ((this.getAubodname() == castOther.getAubodname()) || (this.getAubodname() != null
				&& castOther.getAubodname() != null && this.getAubodname().equals(castOther.getAubodname())))
				&& ((this.getAutablename() == castOther.getAutablename())
						|| (this.getAutablename() != null && castOther.getAutablename() != null
								&& this.getAutablename().equals(castOther.getAutablename())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAubodname() == null ? 0 : this.getAubodname().hashCode());
		result = 37 * result + (getAutablename() == null ? 0 : this.getAutablename().hashCode());
		return result;
	}

}
