package com.poc.domain;

// default package
// Generated Jun 7, 2016 5:01:25 PM by Hibernate Tools 4.3.1.Final

/**
 * AudtbAuditcolumns generated by hbm2java
 */
public class AudtbAuditcolumns implements java.io.Serializable {

	private AudtbAuditcolumnsId id;
	private String auauditflag;
	private String auschemaname;
	private String autriggerflag;

	public AudtbAuditcolumns() {
	}

	public AudtbAuditcolumns(AudtbAuditcolumnsId id, String auauditflag, String autriggerflag) {
		this.id = id;
		this.auauditflag = auauditflag;
		this.autriggerflag = autriggerflag;
	}

	public AudtbAuditcolumns(AudtbAuditcolumnsId id, String auauditflag, String auschemaname, String autriggerflag) {
		this.id = id;
		this.auauditflag = auauditflag;
		this.auschemaname = auschemaname;
		this.autriggerflag = autriggerflag;
	}

	public AudtbAuditcolumnsId getId() {
		return this.id;
	}

	public void setId(AudtbAuditcolumnsId id) {
		this.id = id;
	}

	public String getAuauditflag() {
		return this.auauditflag;
	}

	public void setAuauditflag(String auauditflag) {
		this.auauditflag = auauditflag;
	}

	public String getAuschemaname() {
		return this.auschemaname;
	}

	public void setAuschemaname(String auschemaname) {
		this.auschemaname = auschemaname;
	}

	public String getAutriggerflag() {
		return this.autriggerflag;
	}

	public void setAutriggerflag(String autriggerflag) {
		this.autriggerflag = autriggerflag;
	}

}
