package com.poc.domain;
// default package
// Generated Jun 7, 2016 5:01:25 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AudtbChangedetailsId generated by hbm2java
 */
public class AudtbChangedetailsId implements java.io.Serializable {

	private String aubranchcode;
	private String auresourceid;
	private Date audatetime;
	private String auuserid;
	private int auaction;
	private int aucolumnseq;
	private Integer aulogsequence;
	private String aucolumnname;
	private String aunewvalue;
	private String auoldvalue;
	private String auchannel;
	private String auobjectid;
	private Date aubusinessdttm;

	public AudtbChangedetailsId() {
	}

	public AudtbChangedetailsId(Date audatetime, int auaction, int aucolumnseq) {
		this.audatetime = audatetime;
		this.auaction = auaction;
		this.aucolumnseq = aucolumnseq;
	}

	public AudtbChangedetailsId(String aubranchcode, String auresourceid, Date audatetime, String auuserid,
			int auaction, int aucolumnseq, Integer aulogsequence, String aucolumnname, String aunewvalue,
			String auoldvalue, String auchannel, String auobjectid, Date aubusinessdttm) {
		this.aubranchcode = aubranchcode;
		this.auresourceid = auresourceid;
		this.audatetime = audatetime;
		this.auuserid = auuserid;
		this.auaction = auaction;
		this.aucolumnseq = aucolumnseq;
		this.aulogsequence = aulogsequence;
		this.aucolumnname = aucolumnname;
		this.aunewvalue = aunewvalue;
		this.auoldvalue = auoldvalue;
		this.auchannel = auchannel;
		this.auobjectid = auobjectid;
		this.aubusinessdttm = aubusinessdttm;
	}

	public String getAubranchcode() {
		return this.aubranchcode;
	}

	public void setAubranchcode(String aubranchcode) {
		this.aubranchcode = aubranchcode;
	}

	public String getAuresourceid() {
		return this.auresourceid;
	}

	public void setAuresourceid(String auresourceid) {
		this.auresourceid = auresourceid;
	}

	public Date getAudatetime() {
		return this.audatetime;
	}

	public void setAudatetime(Date audatetime) {
		this.audatetime = audatetime;
	}

	public String getAuuserid() {
		return this.auuserid;
	}

	public void setAuuserid(String auuserid) {
		this.auuserid = auuserid;
	}

	public int getAuaction() {
		return this.auaction;
	}

	public void setAuaction(int auaction) {
		this.auaction = auaction;
	}

	public int getAucolumnseq() {
		return this.aucolumnseq;
	}

	public void setAucolumnseq(int aucolumnseq) {
		this.aucolumnseq = aucolumnseq;
	}

	public Integer getAulogsequence() {
		return this.aulogsequence;
	}

	public void setAulogsequence(Integer aulogsequence) {
		this.aulogsequence = aulogsequence;
	}

	public String getAucolumnname() {
		return this.aucolumnname;
	}

	public void setAucolumnname(String aucolumnname) {
		this.aucolumnname = aucolumnname;
	}

	public String getAunewvalue() {
		return this.aunewvalue;
	}

	public void setAunewvalue(String aunewvalue) {
		this.aunewvalue = aunewvalue;
	}

	public String getAuoldvalue() {
		return this.auoldvalue;
	}

	public void setAuoldvalue(String auoldvalue) {
		this.auoldvalue = auoldvalue;
	}

	public String getAuchannel() {
		return this.auchannel;
	}

	public void setAuchannel(String auchannel) {
		this.auchannel = auchannel;
	}

	public String getAuobjectid() {
		return this.auobjectid;
	}

	public void setAuobjectid(String auobjectid) {
		this.auobjectid = auobjectid;
	}

	public Date getAubusinessdttm() {
		return this.aubusinessdttm;
	}

	public void setAubusinessdttm(Date aubusinessdttm) {
		this.aubusinessdttm = aubusinessdttm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AudtbChangedetailsId))
			return false;
		AudtbChangedetailsId castOther = (AudtbChangedetailsId) other;

		return ((this.getAubranchcode() == castOther.getAubranchcode()) || (this.getAubranchcode() != null
				&& castOther.getAubranchcode() != null && this.getAubranchcode().equals(castOther.getAubranchcode())))
				&& ((this.getAuresourceid() == castOther.getAuresourceid())
						|| (this.getAuresourceid() != null && castOther.getAuresourceid() != null
								&& this.getAuresourceid().equals(castOther.getAuresourceid())))
				&& ((this.getAudatetime() == castOther.getAudatetime()) || (this.getAudatetime() != null
						&& castOther.getAudatetime() != null && this.getAudatetime().equals(castOther.getAudatetime())))
				&& ((this.getAuuserid() == castOther.getAuuserid()) || (this.getAuuserid() != null
						&& castOther.getAuuserid() != null && this.getAuuserid().equals(castOther.getAuuserid())))
				&& (this.getAuaction() == castOther.getAuaction())
				&& (this.getAucolumnseq() == castOther.getAucolumnseq())
				&& ((this.getAulogsequence() == castOther.getAulogsequence())
						|| (this.getAulogsequence() != null && castOther.getAulogsequence() != null
								&& this.getAulogsequence().equals(castOther.getAulogsequence())))
				&& ((this.getAucolumnname() == castOther.getAucolumnname())
						|| (this.getAucolumnname() != null && castOther.getAucolumnname() != null
								&& this.getAucolumnname().equals(castOther.getAucolumnname())))
				&& ((this.getAunewvalue() == castOther.getAunewvalue()) || (this.getAunewvalue() != null
						&& castOther.getAunewvalue() != null && this.getAunewvalue().equals(castOther.getAunewvalue())))
				&& ((this.getAuoldvalue() == castOther.getAuoldvalue()) || (this.getAuoldvalue() != null
						&& castOther.getAuoldvalue() != null && this.getAuoldvalue().equals(castOther.getAuoldvalue())))
				&& ((this.getAuchannel() == castOther.getAuchannel()) || (this.getAuchannel() != null
						&& castOther.getAuchannel() != null && this.getAuchannel().equals(castOther.getAuchannel())))
				&& ((this.getAuobjectid() == castOther.getAuobjectid()) || (this.getAuobjectid() != null
						&& castOther.getAuobjectid() != null && this.getAuobjectid().equals(castOther.getAuobjectid())))
				&& ((this.getAubusinessdttm() == castOther.getAubusinessdttm())
						|| (this.getAubusinessdttm() != null && castOther.getAubusinessdttm() != null
								&& this.getAubusinessdttm().equals(castOther.getAubusinessdttm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAubranchcode() == null ? 0 : this.getAubranchcode().hashCode());
		result = 37 * result + (getAuresourceid() == null ? 0 : this.getAuresourceid().hashCode());
		result = 37 * result + (getAudatetime() == null ? 0 : this.getAudatetime().hashCode());
		result = 37 * result + (getAuuserid() == null ? 0 : this.getAuuserid().hashCode());
		result = 37 * result + this.getAuaction();
		result = 37 * result + this.getAucolumnseq();
		result = 37 * result + (getAulogsequence() == null ? 0 : this.getAulogsequence().hashCode());
		result = 37 * result + (getAucolumnname() == null ? 0 : this.getAucolumnname().hashCode());
		result = 37 * result + (getAunewvalue() == null ? 0 : this.getAunewvalue().hashCode());
		result = 37 * result + (getAuoldvalue() == null ? 0 : this.getAuoldvalue().hashCode());
		result = 37 * result + (getAuchannel() == null ? 0 : this.getAuchannel().hashCode());
		result = 37 * result + (getAuobjectid() == null ? 0 : this.getAuobjectid().hashCode());
		result = 37 * result + (getAubusinessdttm() == null ? 0 : this.getAubusinessdttm().hashCode());
		return result;
	}

}
