package com.poc.domain;
// Generated Jun 7, 2016 5:01:25 PM by Hibernate Tools 4.3.1.Final

/**
 * AudtbBodmap generated by hbm2java
 */
public class AudtbBodmap implements java.io.Serializable {

	private AudtbBodmapId id;

	public AudtbBodmap() {
	}

	public AudtbBodmap(AudtbBodmapId id) {
		this.id = id;
	}

	public AudtbBodmapId getId() {
		return this.id;
	}

	public void setId(AudtbBodmapId id) {
		this.id = id;
	}

}
