package com.poc.domain;

// default package
// Generated Jun 7, 2016 5:01:25 PM by Hibernate Tools 4.3.1.Final

/**
 * AudtbAuditcolumnsId generated by hbm2java
 */
public class AudtbAuditcolumnsId implements java.io.Serializable {

	private String autablename;
	private String aucolname;

	public AudtbAuditcolumnsId() {
	}

	public AudtbAuditcolumnsId(String autablename, String aucolname) {
		this.autablename = autablename;
		this.aucolname = aucolname;
	}

	public String getAutablename() {
		return this.autablename;
	}

	public void setAutablename(String autablename) {
		this.autablename = autablename;
	}

	public String getAucolname() {
		return this.aucolname;
	}

	public void setAucolname(String aucolname) {
		this.aucolname = aucolname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AudtbAuditcolumnsId))
			return false;
		AudtbAuditcolumnsId castOther = (AudtbAuditcolumnsId) other;

		return ((this.getAutablename() == castOther.getAutablename()) || (this.getAutablename() != null
				&& castOther.getAutablename() != null && this.getAutablename().equals(castOther.getAutablename())))
				&& ((this.getAucolname() == castOther.getAucolname()) || (this.getAucolname() != null
						&& castOther.getAucolname() != null && this.getAucolname().equals(castOther.getAucolname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAutablename() == null ? 0 : this.getAutablename().hashCode());
		result = 37 * result + (getAucolname() == null ? 0 : this.getAucolname().hashCode());
		return result;
	}

}
